### ISSUE TITLE
Update for 128?

### ISSUE THREAD

**Issue by barryburd** [ganast/tidybird#114]
When will there be a Tidybird update for Thunderbird 128?

**Comment by MBS17** [comment]
+1

**Comment by MBS17** [comment]
> When will there be a Tidybird update for Thunderbird 128?

I did as suggested here and it worked.

https://github.com/ganast/tidybird/pull/113#issuecomment-2301334534

**Comment by tatankat** [comment]
A new release is made for 128 now.
