### ISSUE TITLE
Button Order after Update

### ISSUE THREAD

**Issue by RandH1607** [ganast/tidybird#115]
Very much appreciate the recent Compatibility Update for Thunderbird 128.

Previously the button order self-sorted to alphabetical, following the update it appears to be random - I don't think it is 'last used' at the top.

The ordered list makes it much easier to use Tidybird, so I'm wondering if the loss of a sorted list is an unintended result of the update. It may be something which is being worked on but you wanted to get the plugin update available a.s.a.p. and then iron out the smaller problems.

Hope this comment is helpful.

**Comment by tatankat** [comment]
Thanks for the report. I reverted back to the old way in version 4.7.1, you can already download it from here.
It was indeed an unintended result caused by using the newer thunderbird api.
