### ISSUE TITLE
dark Thunderbird theme = unreadable Tidybird

### ISSUE THREAD

**Issue by boldcompany** [ganast/tidybird#16]
If using a dark theme in Thunderbird (such as the Default theme when Windows theme is dark), the Tidybird buttons become almost unreadable:

![image](https://user-images.githubusercontent.com/1261048/110393381-0f651380-8030-11eb-8e3c-20feefebeee3.png)

There does not appear to be a UI-config way to fix this in Tidybird.

**Comment by tatankat** [comment]
Can you try [release v2.1](https://github.com/ganast/tidybird/releases/download/v2.1/tidybird-2.1.xpi) and verify if it's better? It should take better colors of the box.

**Comment by boldcompany** [comment]
Hi tatankat - thank you for such a quick reply and attempted fix.

After updating to 2.1, the colors appear to be the same (black text on a dark grey background).

**Comment by tatankat** [comment]
Well, that's strange.

What version of Thunderbird are you using?
Are you using the default "Dark" theme?
Are you sure you are running 2.1?
Have you tried restarting Thunderbird after uninstall and reinstall?

**Comment by boldcompany** [comment]
Hi tatankat - thanks for the followup.

I had previously disabled and enabled the new 2.1 version, and it was still showing the old color scheme.
However, I just tried fully restarting Thunderbird, and Tidybird is now showing buttons with a dark grey background and white text.

Looks good! Thank you very much.
