### ISSUE TITLE
Thunderbird 60.9 broke it

### ISSUE THREAD

**Issue by LongChair** [ganast/tidybird#2]
Tidybird was working fine up to now for me but 60.9 just broke it.

The pane with the buttons doesn't show up anymore... 

Any chance you could have a look at a fix ? :)

**Comment by tatankat** [comment]
I have fixed it for TB68 and now again for TB78.
I hope @ganast comes back and releases them on the addons.thunderbird site.

@ganast maybe I can do the releases for you?

**Comment by LongChair** [comment]
Would have been really cool to be able to continue using it.

@ganast would you consider reviewing the PR that @tatankat made to keep it supported ? :)

**Comment by tatankat** [comment]
I took contact with @ganast and now we are working together, making new releases. Thanks @ganast !

The TB68 version is already officially available on the addon site, which works on TB 60.2.1 and above. It should fix your issue with TB 60.9 ;)
A TB78 version is also on its way!

Thanks for reporting.

**Comment by LongChair** [comment]
I moved to TB78, and will be happy to use tidybrid again when you make it available, thanks.

Really looking forward to the release :)

**Comment by tatankat** [comment]
It is released for TB78 now.
