### ISSUE TITLE
Tooltip background affected by external style change

### ISSUE THREAD

**Issue by noyannus** [ganast/tidybird#82]
The tooltip background is apparently set by some external css. This messes up the appearence, if changes have been made there.

![Screenshot](https://user-images.githubusercontent.com/6339921/201033213-66e5a3e0-3444-41ef-9e00-5a0a7a114658.png)

An independend css might help.

**Comment by tatankat** [comment]
Should be fixed by a225c06aa57ee30bd9ba1f243aa1d5b32a76dc64
This will be part of v4.5, soon available as automatic update. Now already at https://github.com/ganast/tidybird/releases/tag/v4.5
Can you test and give feedback? Thanks.

**Comment by noyannus** [comment]
Thanks for fixing.

The buttons look OK.

![image](https://github.com/ganast/tidybird/assets/6339921/29879a1c-73b7-4ce9-b7dc-400efe31d2f9)


But I cannot set preferences. 

![image](https://github.com/ganast/tidybird/assets/6339921/df16767d-26ee-4827-8fa5-267f5cfdcfa8)


Tested on 
115.2.2 (64-Bit)
Mozilla Thunderbird for Manjaro LinuxManjaro - 1.0

**Comment by tatankat** [comment]
Thanks for testing and the confirmation.
You can't open the settings because there are no settings yet. There may be some available soon.
If you miss some setting, please open a new issue or express your desire for an already existing demand in the issues.

**Comment by noyannus** [comment]
OK.
Thanks, and a nice weekend!
